spring:
  application:
    name: shop-inventory-service
  data:
    mongodb:
      database: shop_db
      uri: ${URI}
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka